# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  working-directory:
    description: 'Directory of SAM application'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working-directory }}