version: '3'
services:
  sam_build:
    build: 
      context: .
    command: /src ${PACKAGE_NAME}
    volumes:
      - ${SOURCE_CODE_DIR}:/src
    environment:
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}